TIP

diff --git a/.github/workflows/check-licenses.yml b/.github/workflows/check-licenses.yml
--- a/.github/workflows/check-licenses.yml
+++ b/.github/workflows/check-licenses.yml
@@ -38,7 +38,6 @@ jobs:
 
       - name: Run License Checker
         id: checker
-        continue-on-error: false
         uses: ./.github/actions/license-check
         with:
           config-file-path: ./.licensechecker.yml
@@ -51,3 +50,9 @@ jobs:
         with:
           name: ${{ steps.checker.outputs.notice-file-path }}
           path: ${{ steps.checker.outputs.notice-file-path }}
+
+      - name: Fail workflow if notice file is dirty
+        if: ${{ steps.checker.outputs.notice-file-is-dirty == 'true' }}
+        run: |
+            echo "::error::Check-in updated ${{ steps.checker.outputs.notice-file-path }} to continue!"
+            exit 1
